{% set name = "line_profiler" %}
{% set version = "2.1.2" %}
{% set checksum = "efa66e9e3045aa7cb1dd4bf0106e07dec9f80bc781a993fbaf8162a36c20af5c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - kernprof=kernprof:main

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - setuptools

  run:
    - python
    - ipython >=0.13

test:
  imports:
    - kernprof
    - line_profiler
    - line_profiler_py35  # [py>34]

  commands:
    - kernprof --help
    - python -m kernprof --help
    - python -m line_profiler --help

about:
  home: https://github.com/rkern/line_profiler
  license: BSD
  license_file: LICENSE.txt
  summary: Line-by-line profiling for Python
  description: |
    line_profiler will profile the time individual lines of code take to execute.
    The profiler is implemented in C via Cython in order to reduce the overhead of profiling.
  doc_url: https://pypi.python.org/pypi/line_profiler
  doc_source_url: https://github.com/rkern/line_profiler
  dev_url: https://github.com/rkern/line_profiler

extra:
  recipe-maintainers:
    - jakirkham
    - koverholt
