{% set name = "line_profiler" %}
{% set version = "4.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: deb2eb9e9119d911debe23edcec8ea68a2cd70c9e3f753c96aaf4a86ca497e7e

build:
  number: 1
  skip: true  # [py<36]
  script:
    # We can't use CMAKE_GENERATOR implicitly via conda_build_config.yaml, yet,
    # due to https://github.com/AnacondaRecipes/aggregate/pull/182
    - set "CMAKE_GENERATOR=Ninja"  # [win]
    - export CMAKE_GENERATOR=Ninja  # [not (win or (osx and arm64))]
    - export CMAKE_OSX_ARCHITECTURES="arm64"  # [osx and arm64]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - kernprof = kernprof:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - cython 0.29
    - scikit-build 0.15.0
    - setuptools
    - wheel
  run:
    - python
    - ipython >=0.13

test:
  imports:
    - kernprof
    - line_profiler
  requires:
    - pip
  commands:
    - pip check
    - kernprof --help
    - python -m kernprof --help

about:
  home: https://github.com/pyutils/line_profiler
  # line_profiler/timers.c falls under the PSF license
  license: BSD-3-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Line-by-line profiling for Python
  description: |
    line_profiler will profile the time individual lines of code take to execute.
    The profiler is implemented in C via Cython in order to reduce the overhead of profiling.
  doc_url: https://github.com/pyutils/line_profiler
  dev_url: https://github.com/pyutils/line_profiler

extra:
  recipe-maintainers:
    - jakirkham
    - koverholt
