{% set name = "line_profiler" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 2f8352acfedf83f701a564583db5e14d

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - kernprof=kernprof:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - psutil

test:
  imports:
    - kernprof
    - line_profiler

  commands:
    - kernprof --help
    - python -m kernprof --help
    - python -m line_profiler --help

about:
  home: https://github.com/rkern/line_profiler
  license: BSD 3-Clause
  summary: A module for monitoring memory usage of a python program

extra:
  recipe-maintainers:
    - jakirkham
    - koverholt
