# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fr2FPVoTaEx237iVVo1GpVu6LGIhJNLNrTMi2U+RnSirdfkiBASkN8yqksQsWcQmTpZlbOHz3lHaBbj4ymra87/Neeztdc2LlgEoqJtMVUQVtko+L1XbBJBFNdq6z/fTJ6F5WHIr86oQdpkE0yV8WDVFUkGb2kG7ViKIZISxHyHXIVNriWENowNAR+xKBNGmFo5nzZ3gqfj3D758CwkIlU9Kl2cZA6nkO3BiBokQ/fGGb2dr5hFYqUJ5SE0adcmC76Oli58JXmUaz7ci8F1mRjDtpVk3sXp6aAtLUr0RVcgjBuTDqvNLl4K9frOljWjH/gAURDdWI+Hj03ZJZcXeL6tjiveDvz+fWTT3rU5sLJ63mwFo8nHqUcirP0tcPOSkenK86sQfrcdnmp1/5er6ede4tvvEMMVr1JtiUdiop0QHLdtJqpgFQRPO+4Dws+u4RKW3gwiXnw5vkYWtTdXHUUiANcuhlD0YxKPTOx6SvflV+FV9SpYwJ7cInr1G0ee0VHp21PNe1qAlxNlU6tYVmhDx0EqwOrtZx6Vm85k2ZbACLhc7cTQYHdTzBv4wX648/LZMhjljChQCHe1TNLa8RdP+igfG92FJ8gao6WFCkarSzA/VaG4GhnB97huHrmTVVoCzYSOPo6sMIEIasqEBoT4BfHpavkSrlqczBKUPj+Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
