travis:
  secure:
    BINSTAR_TOKEN: DxRLoYuOaHC1yfp0gf3olGOJi2JvWIRBTyKXtH8lBAQa7A+wOJWn5QMU0sW0tly0O8KKcmVHylgguc8FQpfWD27lWwHg9TR6LFoXJCDXlNt/SxKVy025LlZ3r5UrWB9eaCome7ZNvF3+Dky2+hx5/Xdv2g7+t6a/nstdBdoPhBlizwfi6xzn9uYov6e1L4KjJTPxo4Q+L/+uihPKokdorTa2AEXGvKY1EO2IfHRI4YCRy1TnvD1i//IbUs9MxYKJGxwZYAIPd3fdO7FYn5Wozp9zK99S2Ukj4etPIzfCeGm5+iwjbT8sJ4K1hPM7iaA2pc4E4+he7mvhwD84SUXNw52KLYdbkcGZ89uOcQuZ5pr+wkZZV1V17lKWck25kMz/+sYTRXuEScWoNEPdoNdva1xIPp7J2RZ6uwhQCgb5bbQeE4YvByi7Qi+KryuRngQDlEHmzABgppcyQ9xILaqM/xkF0OPcriophlQSTAoX9c56u3e3y/E0Ki2P6n6TptHfgkwAFPaGE6P5WWPUIwIlY1a0QRjvJPt5KhkMAKcphRm1wWZtL8yFBgjmH0U2Au1+WpXg4dgqlMWb/LT7tDj949oZSva6sM4TjCrCTGLBh3IXrQOuRWmiw50N5C8UQM+mwcOvFMyqEmDiHOkgMRMNjF/7UtZ+AnCyijeIGMsz+J4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
